apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  volumes:
  - name: docker-registry-pv-storage
    persistentVolumeClaim:
      claimName: docker-registry-pv-claim
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: docker-registry
        image: registry
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/var/lib/registry/"
          name: task-pv-storage
