apiVersion: v1
kind: Service
metadata:
  name: docker-registry-svc
  namespace: docker-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - name: registry
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31313
    